name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
        working-directory: thereal/client

      # Uncomment this step if you want to check formatting.
      #- name: Verify formatting
      #  run: flutter format --set-exit-if-changed .
      #  working-directory: thereal/client

      - name: Run static analysis
        run: flutter analyze
        working-directory: thereal/client

      # Uncomment this if you have tests to run.
      #- name: Run tests
      #  run: flutter test
      #  working-directory: thereal/client





