name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Flutter App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Java (for Flutter)
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: 'latest'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get
      working-directory: thereal/client

    - name: Analyze project source
      run: flutter analyze
      working-directory: thereal/client

    - name: Run Flutter tests
      run: flutter test
      working-directory: thereal/client







